[package]
name = "test13-52-rustcallcpp"
version = "0.1.0"
authors = ["jiankang.wang <18616290881@163.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = "1.0"
