[package]
name = "test12-46-proc-macro"
version = "0.1.0"
authors = ["jiankang.wang <18616290881@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
proc_macro = true